; world.ini Carnage by Mysti

;DesertSurface=21

SURFACEGROWTH=119

;FACTIONRULES
;TRADERDEATH

;SAVEWORLDCHANGES


;;;; world 

MapSize=2000
WorldDepth=8

StartXpos=450
StartYpos=450
StartZpos=0


ClimbLowElevation=130
ClimbHighElevation=135

SurfaceDamage=18,10,Fire


;;;; setup


OwnerEmail=texgal-4ever@hotmail.com
PopupMotd

PostDelay=90

;EmailMessage=Thanks for playing 
ServerMessage=Entering a world of CARNAGE!!! 

;Disablemail

;RestrictGlobal=true

LogHistory

LogThreshold=15

;NetLog

GlobalChatDelay=15

;PlayerActivation

;DISABLEMACROWARNING





;;;; gameplay setup

;DISABLEAUTOSTALKERS
AUTOSTALKERID=152

;NewCombatRoll

;FORCEPK
Perks

;PerksLoginOnly

TimeToResurrect=8
DEATHPROTECTIONTIME=1

PlayerSurfaceCost=5
;DISABLESURFACE



;;; player


SkillPoints=54
AttributePoints=350

SkillRollType=1
SkillRollAlpha=40

AllowImageChange

PKprotectionLevel=10
;NoPKPenalty
pklevelrange=10

VitaePenalty=3

MaxPLayerFood=500

MaxPlayerWater=250

FoodOnDeath=50

PassedOutImage=359

AllowTopTen


;;;; network

ServerPort=4502

DisableClientSecurity

PPSLimit=150

;ClientRestricted
;maxallowedclients=10

AllowDupIPClients=False

MaxPlayerPerClient=2

MAXDUPIP=1


;;;;; monsters

MobEffect=6
DISABLEOPTIMIZEDMONSTERMOVES
Bitch
Monsterspread=32
Monsterchase=20
MonsterProcessSeconds=2
MonsterSpawnProcessSeconds=20
MonsterSpawnCount=15

DefaultMonsterSpeed=1.5
MaxPoison=200


;;;; saving
;HourlyWorldSaves
;AutoShutDown=3


;;;; tribunal
;TribunalAdminApprovalRequired
;TribunalRules
;TribunalMode=0


;;;; items
ItemMapStackLimit=20

repairdegrade=0

;ItemsStealable

ItemStackLimit=100000
ItemMapStackLimit=20

ItemOwnerDecay=60

MAXITEMSKILLBONUS=50



;;;; starter items


;StarterItem=316



;;;;; growth

SPEEDUPGROWTH=4

;SPEEDUPGROWTH=-1
;SPEEDUPGROWTH=2     ;;; horizon old
;SPEEDUPGROWTH=4     ;;; Hexed
; -1 is every 4 seconds

NoSeasons


;;;;; XP

XPFactorCombat=1.0
XPFactorTrade=1.0

;;XPFactorCombat=0.40    ;;; horizon old



;;;;; access and admin
;AdminOnly

;;;;;@@@Admins

UltraAdmin=stonegate

SecretClient=stonegate2


;;;;;@@Admins
;SuperAdmin=


;;;;;@Admins
;Admin=



;;;;; Land

disablenewbieisland
OpenReservedLand

UsableUnClaimedLand

maxunclaimcount=1000

maxlandown=1

landclaimcost=1000

LandOwnerTimeToLiveDays=1080


;;;; meteor

;damonite meteorite
MeteoriteItem=1464

;MeteoriteRate=2
;MeteoriteSize=4
;MeteoriteSpawn=2

;;;; mining

MiningBraceSurface=157

MiningDepthMax=8
MiningDepthFactor=20

CaveInItemDestroy


;;;; traders

MaxTameCount=20

NPCTraderstartgold=0

TraderBuyMax=5
TraderBuyCost=1000

NPCIdletimeout=-1

TameShareXPPercent=2



;;;;; guild

;GuildTown
;AutoGuildTownClaim
;DisableGuildQuit


GuildCreateCost=5000
GuildCreateLevel=10
GuildMaintainCost=100
GuildXPPercent=.15
GuildLandClaimCost=5000


;;;; magic


;; black
StarterSpell=208
StarterSpell=185

;; white
StarterSpell=1
StarterSpell=16

;; red
StarterSpell=92

;; blue
StarterSpell=146
StarterSpell=147


;;;; scripts


CTFREDIMAGE=500
CTFBLUEIMAGE=499

CTFREDRESURRECT=1189,72,0
CTFBLUERESURRECT=1129,11,0